### ISSUE TITLE
Q: Possible to apply formatting to input?

### ISSUE THREAD

**Issue by Ljupch0** [INWTlab/shiny-matrix#11]
Hi, thanks for the great package.

My question is whether the inputs can be styled.

Ex. A user inputs 1365845, which is styled as 1,365,845.00 after the user inputs it? 

Do you have an idea how to do this?

Thanks again.

**Comment by aneudecker** [comment]
Hi @Ljupch0, glad you like it!

You could apply custom CSS styling to your matrix input field. However it seems there is no CSS attribute to format numbers in the way you want it. Also using external JavaScript is not really an option because you would need to add additional click handlers to the cell which will make things complicated ... 

The proper way to implement it is within shiny-matrix itself:

- add a parameter to the `matrixInput` function
- parse the content in https://github.com/INWTlab/shiny-matrix/blob/master/inst/www/matrixInput.js#L377 according to the option
- format it to your liking at https://github.com/INWTlab/shiny-matrix/blob/195e385ce43fbda7bfa9992583c232ee2e43cad3/inst/www/matrixInput.js#L282

In won't have time implementing it anytime soon but PRs are welcome

**Comment by Ljupch0** [comment]
Great, thanks for the help, might give it a try.
