### ISSUE TITLE
Enforcing input restrictions

### ISSUE THREAD

**Issue by factoryofthesun** [INWTlab/shiny-matrix#14]
Hi, 

Do you know how I would be able to go about applying input rules (e.g. every row must sum to 1, no negative numbers, etc.)?

Great package. Thanks!

**Comment by aneudecker** [comment]
Hi @factoryofthesun, glad you like this package.

The only input check implemented in JavaScript right now is the check whether the values are numeric if the `class` parameter is set to numeric. Right now it is not possible to add own JavaScript functions for validation. I would do something like this in shiny. Assuming that the matrix input field is `input$matrix`

```r
function(input, output, session) {
  matrixData <- reactiveVal()

  observeEvent(input$matrix, {
    if (!all(input$matrix >= 0)) {
      shinyjs::alert("All values should be >= 0")
      return()
    }

    if (...) {

    }

    matrixData(input$matrix)
  }
}
```

You can then work with `matrixData` instead of `input$matrix` in your shiny server function.

Instead of using `shiny::alert()` you could also consider to add a textOutput field (output$error) for the error message:

```r
function(input, output, session) {
  matrixData <- reactiveVal()
  errorMsg <- reactiveVal(NULL)

  observeEvent(input$matrix, {
    if (!all(input$matrix >= 0)) {
      errorMsg("All values should be >= 0")
      return()
    }

    if (...) {

    }

    matrixData(input$matrix)
  }

  output$error <- renderText(errorMsg())
}
```

**Comment by factoryofthesun** [comment]
Thanks for the tips! The server-side checks have sufficed as a solution for my use case.
